# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XDmXM9MMSbO6CAVsX3LQP3i2TAmADdtA+BscoUFUmuYxzKx5YY3z2jbaKFXnC1TOoJPcto0JpGYkqgDA5ZjSM9IvJRYJiKW+dvwUxrOpT3+5ykMb5Oq0FC8osE43un6azgoi33TIB9lWc/Q7XCvGVv/X037PM8/gibVI1iE6LdslLwZEKlyuy8tl/Fl0qJ67yQN6uinE4Fcxm0HlilR9kLdoo11zXcRUuedx6SZpBP0cCUXQcrEPxfIKnejjnU/WRBF0cSG60SfjS7SsngPHJkQCpmiOIV5cBG4gJ8Z2s78fOJLbIYCRqIxrCINA5m/rQtxsU+BFAHjcKaEfc15pIqsvrIzda/G6lcVFOif0VtWALiPudqcJtcErqsybR+KXAiYIPHi2BO5cTK7WGOlDK80NLcQeCYjOb954aQY5Ob6OjAdvKEAQSpIlHpbkzgvaxHe4TGhBASI7yj72HwSCecfgApWlCh5+lQgxP0qn3NIXmFiELVKnzQP7Joku36VjrY/nEVBE6+oy6+S2tfL6F54B2kb1QifbxSr4G+gBhN2GDSdSVXkoCqS10Un2E13EmUp2Yym03kw/C8BQhaeoT3ggGXYD89cJjzJSSVAZ/dOJnirXGVzzlXOAMdb8PfExRD7ztFOCbJQacFrd8CHPa+CfeGnzCFmtLo4qW2mdJes="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
