travis:
  secure:
    BINSTAR_TOKEN: XDmXM9MMSbO6CAVsX3LQP3i2TAmADdtA+BscoUFUmuYxzKx5YY3z2jbaKFXnC1TOoJPcto0JpGYkqgDA5ZjSM9IvJRYJiKW+dvwUxrOpT3+5ykMb5Oq0FC8osE43un6azgoi33TIB9lWc/Q7XCvGVv/X037PM8/gibVI1iE6LdslLwZEKlyuy8tl/Fl0qJ67yQN6uinE4Fcxm0HlilR9kLdoo11zXcRUuedx6SZpBP0cCUXQcrEPxfIKnejjnU/WRBF0cSG60SfjS7SsngPHJkQCpmiOIV5cBG4gJ8Z2s78fOJLbIYCRqIxrCINA5m/rQtxsU+BFAHjcKaEfc15pIqsvrIzda/G6lcVFOif0VtWALiPudqcJtcErqsybR+KXAiYIPHi2BO5cTK7WGOlDK80NLcQeCYjOb954aQY5Ob6OjAdvKEAQSpIlHpbkzgvaxHe4TGhBASI7yj72HwSCecfgApWlCh5+lQgxP0qn3NIXmFiELVKnzQP7Joku36VjrY/nEVBE6+oy6+S2tfL6F54B2kb1QifbxSr4G+gBhN2GDSdSVXkoCqS10Un2E13EmUp2Yym03kw/C8BQhaeoT3ggGXYD89cJjzJSSVAZ/dOJnirXGVzzlXOAMdb8PfExRD7ztFOCbJQacFrd8CHPa+CfeGnzCFmtLo4qW2mdJes=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
