travis:
  secure:
    BINSTAR_TOKEN: FghiATQdOY4UQhurn7L2Aco6rf+bKsaj0oC2SlccTmGanUQx/T8ONVXFwxA0TMmAH1J/iQRTbZxk+S58snDGNVGkE7TRXG8B5TEQHKp9s96Osuy8wtlK0rWAAAv0TGCC3sY258lJRejIUV1QSQ9mqIISf85fY9qgVtxB5KqAZ1O9B4w3WItpyYQh1SbnbFmk5sTfr+JUjDtwK8qE8pbMkDavWBQYkTl78c994ZhKAdzcNqnBojtO8VHxacV7ZC0SDU82OiKKmyfr3LZeHQQA14Z19LKgB7HQbFad5uxW2d7V3ZA2QdYA7CmetCmW4cIZsGovCRQ9AvJdO9q60dGgmWJD36R3F6ADwGqpWxXlGDHs4U2Mnq8LY7vauoki1Hc3ImDZ08WOy0eMyst7CclqwfbBZF4BZ7u4P97Z8t7x3Xm9C/UVYPPObSvVNnBfo7MbKOkTg6JOgmcas1KjiH6Uf8VIHNFZJ+OY5UAIl7q1RWKwwH9/TZPoaKUONgLnBpuSLTevuwAEJrFjxfNm1K2vL4UXn4vcrnlfByFAoVao3AuLXbmKvB8GQDtrshI3rvDUA7gvHgT/p0sMDQrWCGyOBrTELzh2FacHWe4yKfA6O6IQRACG7Mqqk9JskLtxgzn7st7J+LUCFGOYzbxikwnr3jzgo4e/RbUDqRC9dQDWZl8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
