travis:
  secure:
    BINSTAR_TOKEN: ZzTrGH6YjO4QYpa3i8k8d2kIdwtyxsQbRFGfXwBe9X82hx10XoX0j32lwJPndJga37sSgE4wvpR2OSVVTkI+Y36sfFdvwvsPw9e6Hyl8+MLJOmdURW0LDv5s1Ln0/AamFKiY+f8+g7IwTefs/sUGP1CiaM8bojmxaATcyvxnUwyIAZBwwM/zw1H5QJSrZ2DAuOrDY6FZ/CLx7oWnAMrZrfYRV3ni2Oebvc6pfJoBW0+dzozNEwza63LnVCCOA64dcKGAy4KQuKtjJyiaI9k1AIw+f5GvkqyUdbzC27OGslAiUjO4p1+KssK3OkgunHRoR656gdaz+JH55ReG+5+lgtuEv7b7UPvOzAjk01RofmpZTBKu/kOtwbYOTdvQyjWxTk7/O+h9iXhe31IQJrIj3a9xSbR9dwPB+5On7hcMHobzD4AszU7zuN+hHK7nQrrb4rf6kUqPeSuBPT/V18oZ9ApRGAR1xB2p/hBgfMkr6WeKIxNh67Nfxy5l+ZrBAJVpYyCACILiWWaW1JDGB9XrYCN6Cx41oOvjLKTkQJ3LfXCsBd5kJBQQf8UBhVSfDjAQfJlj3fWSTFAIb+xbypMug0e+F4PCTUKuiTfFRdLB96G4j0ruqES0a6zqOHjSgGKNd/2EC2Hg+JbHueTMlCNDmz2n/2T23rBAN5xH6XJbP4g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
