travis:
  secure:
    BINSTAR_TOKEN: QU3DiBV3tqwlDqKCpS+m+d/yWQH00pd2tddjMfw+htUh6oW1pJ2TD2amInRa9baMXMC0ekCIRcy6O+8qMoCkwo3uugHPCf/OSHGnPgCcpQQLHTEXuUlh0jn8ApKXoriZy32mf3lk4dy9rUFucOinyrPUtr3v+HGRSUM/famOgC1FIuKmZ7pOxbMG8HkJFpnaaDOWkbKp9MtAg+tRgVOfibMXZ8/UnTnMECH8J8TK5qsAsn71S5JZGzvxoo7Yzjl/EuTiGoArNYOeVe4wgg7hudYkdE4LrchlRmf4qwoM39W/ffF2eQ27EfBcVhnG7PT5Z0aX2asvCz88O1oJi2ZJHUi4KrPfBRGEiN5X4Gstnc1wHxJ1UZ6sqH1cY6UnQbwRTvb93hIKPjvOiKeYIoKrOAxmFBQXiy/Jy1sWwPlhjR/1NMYea4Putz5XzLaH+EmBCVKQJ4z99+wnaOgqL4hYsQeGK4Os/Ycm5XePgGCmuVtVGoNYT2uIJcGK9baev3MoDljc+WJT1bGsDRhDaVDC2CCM6FNFD36IwBeFaUT7VasFMXt191dULzZRMl1l2fYepNfBWTijRztv1NQ+Nat2OfOVLnrA+8ChCIsmY6uDCBQVjeVi8hwGz/0li1HO44epayc2p6vGu7J7qDw9XmM2ALjTMuoNj3IufuNdljok91A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
