travis:
  secure:
    BINSTAR_TOKEN: TUTRQomWSxRXRNbCDHBXQoALfCUg5r8xTHm+upOG+f7nwfho54tMP96oLTy6WF6igHilfr8MFwx8NbhDSd+/f4IZsrJu1Kt/bwa3NygQ2dcYmo2xPkp0/Uu9P7QMaZWPWCSGs2OxQEykfKKSNsDknPuM3hwv6+id8kg6xpyGWa8Cn6w+gbgJNjcuEMOfMXW3UMEdtk2KdCne/M5McOysk/8plku1/KlMyb959LJJJ9O1ZGumJbijqo0+qDX/DNoifQZRkUOV/lnjlILbgPb9hsUZAX/806P9eBVMPnpjVcSR4NfSueOpMGFVM/VD1S+no+1akq7DqafvE24VJcJlFa9mrww32JdQq+FxVgsiGTaP2rT4xMR4Ar6k/cKFBt7sUDqWDbGUfdraIjsDYWfSpBy4pCwhmM9zga4Xku/9g4KHiqsGgN2tQZTj14tE7M8rqnI2NUSdC/mrQWwDWo0w3KvFYMbYTaNlaAxTcXg5zy4iTzYtRqdBhh+XJ0d0iK2M8hFKDSNFIZL5oqJyAmBIwRGsreqbSotnM/Ar5xrDuqjY0pF0bhj3LjYQS3uEnRBXdCnawRNN+PGFAud4MQ/lpwjGcC0UqLqG065pMWAMWFuiorolj8jM8p0ejk51NSufd0rLkcrt7/cHdHacp2LFhmQDSETCmt0uWizDubioFtI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
