travis:
  secure:
    BINSTAR_TOKEN: YeD7KS3/Uutm79gzLBuSkLydJzm5rLeHhqZPui2GCHYJZMJ+KwAamCzv17dVuXa9pwnqJiat1l4d2SYzdyNjjpnbMimr4EKycRXH9xzHXW1z4kmoI2+yVTDckhaYTLj0vK/v8ft2jR3qc5+ck+6B7+WLTQnQwqJCkRVhGZtmk2VHuUrrj7xhU8GXV3vqHP0eN52PgVZegSUIRBES5RS2In3NsSoYJOnbfwKzN6zknvzve8ku5pD2NY/OaK3n7peRQ2pHnm4xfhSk0gGcE1BJyinG6xLt89KrqqplxAUV12+COdhMSyD+a5cBjGMxFSpqINuU7dlAjOJbAIx4lK4FxIAV2dt0RVy5TEOi6zTTqWpQxTnD9oyDQ/4+dPpGJ8XTiK/yLckFJ3/4RdhBhBG5J79id2sZyVVVGKeSOtwzys/nF92JfPcZRaQo9HqsSDFxinayP6VtIur7eYboynooSe4MsWLDUX7m2RByhwldbEc3LNCQJnlfQ9p7eAfdcd5Dyf/gCSLRFGx6URDvQ3ghk17BcXHYYE+i65g/hNJzpNvJvH7Xp19r0LcpuQzqR+0C/D0ZFXDWsG6nzPYhsxTI5QkYWeDl1GGt/sP+93UvFViEJFVF1GCy9XcxjaDhdltVLrD4vDveIdkeMi+eSorEnY5wkFyWgT+atucbEcAjzfU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
